CREATE DATABASE Garagem
GO
USE Garagem
GO

CREATE TABLE CARRO(
	Placa CHAR (7) NOT NULL,
	Nome VARCHAR (30) NOT NULL,
	AnoModelo INT NOT NULL,
	AnoFabricacao INT NOT NULL,
	Cor VARCHAR(20),
	CONSTRAINT PK_CARRO PRIMARY KEY (Placa)
);
GO

CREATE TABLE SERVICO(
	Id INT IDENTITY(1,1),
	Descricao VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SERVICO PRIMARY KEY (Id)
);
GO

CREATE TABLE CARRO_SERVICO (
	Id INT IDENTITY(1,1),
	Carro CHAR (7) NOT NULL,
	Servico INT NOT NULL,
	[Status]  BIT
	CONSTRAINT PK_CARRO_SERVICO PRIMARY KEY (Id),
	CONSTRAINT FK_CARRO_CarroServico FOREIGN KEY (Carro) REFERENCES CARRO (Placa),
	CONSTRAINT FK_SERVICO_CarroServico FOREIGN KEY (Servico) REFERENCES Servico (Id)
);
GO